library(ahp)
mackAhp <- Load('C:/Users/rafku/Documents/do r/ahp2.ahp')
Calculate(mackAhp)
print(mackAhp, priority = function(x) x$sparent$priority["total", x$name])
Visualize(mackAhp)
Analyze(mackAhp)
AnalyzeTable(mackAhp)
AnalyzeTable(mackAhp, decisionMaker = "Ojciec")
AnalyzeTable(mackAhp, decisionMaker = "Matka")